CREATE DATABASE GAMMA_AIRLINE_TEST;

USE GAMMA_AIRLINE_TEST;

DROP TABLE USER IF EXISTS;
DROP TABLE BANK_ACCOUNT IF EXISTS;
DROP TABLE USER_TICKET IF EXISTS;
DROP TABLE EMAIL_DATA IF EXISTS;

CREATE TABLE USER (
    USER_ID INT NOT NULL auto_increment,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    USER_ROLE VARCHAR(10) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    VERSION INT(3),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_ACCOUNT (
    ID INT NOT NULL auto_increment,
    USER_ID INT(10) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    VERSION INT(3),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID)
    REFERENCES USER(USER_ID) ON DELETE CASCADE
);


CREATE TABLE USER_TICKET (
    ID INT NOT NULL auto_increment PRIMARY KEY,
    USER_ID INT(10) NOT NULL,
    ORIGIN VARCHAR(50) NOT NULL ,
    DESTINATION VARCHAR(50) NOT NULL,
    PRICE INT(10) NOT NULL,
    CURRENCY VARCHAR(5) NOT NULL,
    TICKETS_AMOUNT INT(5) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    VERSION INT(3)
);



